import { Aleo} from "next/font/google";
import "./globals.css";

import Header from '../src/Component/Header/Header.jsx'
import Footer from '../src/Component/Footer/Footer.jsx'

const aleo = Aleo({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={aleo.className}>
        <Header title = "Fireplace Palace"></Header>
        {children}
        <Footer />
      </body>
    </html>
  );
}
